import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { api } from "~/utils/api";
import React from "react";

const Home: NextPage = () => {
  const { data: sales = [] } = api.sales.getAll.useQuery();
  const { mutate: createSale } = api.sales.create.useMutation();
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Create <span className="text-[hsl(280,100%,70%)]">T3</span> App
          </h1>
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:gap-8">
            <button
              className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
              onClick={() =>
                createSale({
                  item: "Second Item created",
                  price: 1000,
                  quantity: 5,
                })
              }
            >
              <h3 className="text-2xl font-bold">Create new Sale</h3>
            </button>
            <Link
              className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
              href="https://create.t3.gg/en/introduction"
              target="_blank"
            >
              <h3 className="text-2xl font-bold">Documentation →</h3>
              <div className="text-lg">
                Learn more about Create T3 App, the libraries it uses, and how
                to deploy it.
              </div>
            </Link>
          </div>
          <ul className=" grid grid-cols-4 gap-6">
            {sales.map((sale) => {
              return (
                <li
                  key={sale.id}
                  className="container flex flex-col items-center justify-center gap-2 rounded-lg bg-white/10 px-8 py-6 text-white"
                >
                  <span className="text-[hsl(280,100%,70%)]">{sale.item}</span>
                  <span>Price: ${sale.price}</span>
                  <span>Quantity: {sale.quantity}</span>
                </li>
              );
            })}
          </ul>
        </div>
      </main>
    </>
  );
};

export default Home;
